defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  run:
    dir: ${oc.env:HYDRA_OUTPUT_DIR,./outputs}/${dataset}/seed${seed}/${job_name}/${hydra.job.override_dirname}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - seed
          - experiment
          - eval_only
          - ray_cpu
          - ray_gpu
          - grace_period
          - lam_reg
          - k_reg
          - alpha_test
  sweep:
    dir: ${oc.env:HYDRA_OUTPUT_DIR,./outputs}
    subdir: ${dataset}/seed${seed}/${job_name}_temp${temperature}_steep${steepness}
